### PR TITLE
Add support for buildargs in POST /build.

### PR DESCRIPTION
**Pull request by pwnall**
I want this to try to implement affinity support for building images into swarm.
https://github.com/docker/swarm/issues/1282

I didn't find any test for BuildImage. I'm willing to try to write one, with a bit of guidance.

My code is very similar to the one in Docker's api/client package, so maybe I can get away with that?
https://github.com/docker/docker/blob/ef4b053b9064888eadf25e48f7f1d4d5896da8fb/api/client/build.go#L271

Thank you for taking a look at this!

### CODE REVIEW

**Comment by abronan** [comment]
LGTM

ping @vieux

**Comment by jimmyxian** [comment]
+1

**Comment by pwnall** [comment]
@vieux Can you please take a look at this? I'd be happy to address your feedback!

**Comment by vieux** [comment]
I'll take a look asap.

**Comment by pwnall** [comment]
Thank you very much! :heart:

**Comment by vieux** [comment]
LGTM

**Comment by pwnall** [comment]
Once again, thanks so much!

**Pull request merged**
