### PR TITLE
use time as string

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <victorvieux@gmail.com>

### CODE REVIEW

**Comment by vieux** [comment]
ping @donhcd

**Comment by ehazlett** [comment]
LGTM

**Comment by donhcd** [comment]
@vieux I'm a bit late to the party but what's the reason for this?

**Comment by vieux** [comment]
Looking at the docker/docker implementation, the server is the one who
choose the encoding.

We did the same in swarm: https://github.com/docker/swarm/pull/1034

I'm not sure the Docker cli can parse a time.Time

**Pull request merged**
