### PR TITLE
Add NetworkSettings field to /containers/json response

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
@abronan Hello, I am adding the `NetworkSettings>Networks` property I introduced in Docker Remote API v1.22 and I will integrate this to Swarm afterwards by updating vended package.

More info: https://github.com/docker/docker/pull/18559 

My end goal is to find out which network each container is in along with its IP address in `/containers/json` response (otherwise I need to query each container's info individually) so that with [wagl](https://github.com/ahmetalpbalkan/wagl) I can provide seamless name resolution for containers in the same overlay network.

Copied `EndpointSettings` from [here](https://github.com/docker/docker/blob/10bbe0ee7ccb3f8e6c37f84b89a887e882f83944/api/types/network/network.go#L24).

### CODE REVIEW

**Comment by abronan** [comment]
Thanks @ahmetalpbalkan,

SGTM when docker/docker#18559 will be merged

**Comment by ahmetalpbalkan** [comment]
@abronan that's now merged.

**Comment by thaJeztah** [comment]
Thanks @ahmetalpbalkan!

**Comment by abronan** [comment]
LGTM

ping @vieux @ehazlett

**Comment by vieux** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
Thanks! I'm having trouble updating the vended version at docker/swarm, I'm getting a nasty error from godep: https://github.com/tools/godep/issues/372.

I tried to do it manually but it's not trivial. The new version of dockerclient comes with `github.com/docker/go-units`, which needs to be vended as well, and other code using `docker/docker/pkg/units` should move to this (and thus remove dependency to `docker/docker/pkg/units`).

If one of you could try, I really appreciate.

**Comment by abronan** [comment]
@ahmetalpbalkan PTAL docker/swarm#1558.

We are updating Godeps as there are a lot of stuff under `docker/pkg` being moved into their own repository.

**Pull request merged**
