### PR TITLE
Add LogConfig and Ulimits(new in docker 1.6).

### PR DESCRIPTION
**Pull request by lingdecong**
Implement the new feature in docker 1.6

dockerclient

Ulimits - A list of ulimits to be set in the container, specified as { "Name": <name>, "Soft": <soft limit>, "Hard": <hard limit> }, for example: Ulimits: { "Name": "nofile", "Soft": 1024, "Hard", 2048 }}

LogConfig - Logging configuration to container, format { "Type": "<driver_name>", "Config": {"key1": "val1"}} Available types:json-file,syslog,none.json-file` logging driver. 

Add two types for HostConfig

### CODE REVIEW

**Comment by lingdecong** [comment]
ping @vieux @abronan

**Comment by donhcd** [comment]
LGTM.

I tested by running `ContainerCreate` with 
```
HostConfig: dockerclient.HostConfig{
                        Ulimits: []dockerclient.Ulimit{
                                {
                                        Name: "nofile",
                                        Soft: 1024,
                                        Hard: 2048,
                                },
                        },
                        LogConfig: dockerclient.LogConfig{
                                Type: "none",
                        },
                },
```
and the `docker inspect` for the created container had the expected Ulimits and LogConfig settings - the default seems to be "json-file" logging and no Ulimits.

**Comment by donhcd** [comment]
ping @aluzzardi @ehazlett

**Comment by vieux** [comment]
LGTM

**Pull request merged**
