### PR TITLE
move VolumeDriver to HostConfig

### PR DESCRIPTION
**Pull request by jimmyxian**
Move VolumeDriver to HostConfig 
This issue (https://github.com/docker/swarm/issues/1339) need this PR 
Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by jimmyxian** [comment]
ping @vieux @abronan

**Comment by vieux** [comment]
@jimmyxian will this work with docker 1.7 or 1.8 ? 

Shoudn't we keep both for compat ?

**Comment by jimmyxian** [comment]
@vieux Thanks. Need to keep. I will fix now. :)

**Comment by jimmyxian** [comment]
ping @vieux 
Review again. Thanks

**Comment by abronan** [comment]
LGTM

ping @vieux

**Comment by vieux** [comment]
LGTM

**Pull request merged**
