### PR TITLE
[WIP][Do not merge] Response body may not close in readJSONStream

### PR DESCRIPTION
**Pull request by dongluochen**
Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by dongluochen** [comment]
ping @vieux @nishanttotla @abronan.

**Comment by nishanttotla** [comment]
@dongluochen is this related to an issue?

**Comment by vieux** [comment]
@dongluochen did you try it with swarm ? works ok ?

**Comment by dongluochen** [comment]
It's related to issue swarm issue #1838. But it doesn't work. After test I don't find TCP leak on `events` with current code. Discarding this PR.

**Pull request closed without merging**
