### PR TITLE
state: Support for String() and StateString()

### PR DESCRIPTION
**Pull request by aluzzardi**
Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>

### CODE REVIEW

**Comment by aluzzardi** [comment]
Do not merge - there is a dependency issue with docker:

```
$ go test ./...
go build github.com/docker/docker/autogen/dockerversion: no buildable Go source files in
FAIL	github.com/samalba/dockerclient [build failed]
?   	github.com/samalba/dockerclient/examples	[no test files]
?   	github.com/samalba/dockerclient/examples/stats	[no test files]
ok  	github.com/samalba/dockerclient/mockclient	0.005s
```

**Comment by tianon** [comment]
That's bizarre though; `pkg/` can only ever include other `pkg/` or things from `vendor/`, so that should work fine (and this particular package is 100% self-contained, so this should be totally fine).

What does your local directory structure look like and what's the value of your `GOPATH` when you're trying to build it?

**Comment by tianon** [comment]
(ie, is `github.com/docker/docker` inside your current directory somewhere?)

**Comment by tianon** [comment]
Ugh, I can actually reproduce this on master.  I wish we could just axe `gccgo` again and call it good, and forget we ever had to even try this autogen crap.

**Comment by aluzzardi** [comment]
My `GOPATH` only contains `~/go`.

You can reproduce this with:
```
mkdir /tmp/go
export GOPATH=/tmp/go
go get github.com/samalba/dockerclient
cd $GOPATH/src/github.com/samalba/dockerclient
git checkout -b aluzzardi-state-string master
git pull https://github.com/aluzzardi/dockerclient.git state-string
go test ./...
```

**Comment by tianon** [comment]
Ahhh:
```
engine_mock_test.go:16: "github.com/docker/docker/utils"
```

That definitely doesn't help.

**Comment by tianon** [comment]
It looks like `utils.NewWriteFlusher` is the only thing being used there -- think it'd be easy to extract into a proper `pkg/`?

**Comment by tianon** [comment]
Heh, it even has a `FIXME`: (https://github.com/docker/docker/blob/74bfa3675353aaf10ca760e82a79d758bea0ff6b/utils/utils.go#L126)
```go
// FIXME: move to httputils? ioutils?
```

**Comment by aluzzardi** [comment]
@tianon Oh right, I didn't even notice this is happening on master as well.

I actually wiped out `github.com/docker` from my `GOPATH` yesterday so I'm starting on a clean state, I assumed the error came from my PR not from a pre-existing thing.

**Comment by aluzzardi** [comment]
Let's carry on with the merge then :)

ping @vieux

**Comment by vieux** [comment]
LGTM

**Pull request merged**
