### PR TITLE
add PushImage()

### PR DESCRIPTION
**Pull request by donhcd**
ping @vieux @aluzzardi @ehazlett 

remaking #97 

example code:

```
package main

import (
        "log"

        "github.com/donhcd/dockerclient"
)

func main() {
        docker, err := dockerclient.NewDockerClient("unix:///var/run/docker.sock", nil)
        if err != nil {
                log.Fatal(err)
        }
        log.Println(docker.PushImage("donhcd/ubuntu", "trusty", &dockerclient.AuthConfig{"donhcd", "password", "email"}))
}
```

### CODE REVIEW

**Comment by divideandconquer** [comment]
@donhcd thanks for rebasing and resubmitting this.

**Comment by vieux** [comment]
@bmangold is this working for you ?

**Comment by toli** [comment]
I'd love this functionality, happy to be your guinea pig if needed

**Comment by bmangold** [comment]
This works for me! To use this, I installed docker 1.8.2 on an ubuntu VM ... exposed the daemon for tcp `DOCKER_OPTS="--host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2376"` , and then configured my goclient to talked to `tcp://my_vm_host:2376`.   I was able to push an image and verify that it appeared in Hub.

**Pull request merged**
