### PR TITLE
Update README.md with the status of the repo.

### PR DESCRIPTION
**Pull request by donhcd**
ping @samalba @vieux @ehazlett

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by thaJeztah** [comment]
ping @bfirsh as well. Guess this closes https://github.com/samalba/dockerclient/issues/238 ?

**Comment by bfirsh** [comment]
:+1:

**Comment by ehazlett** [comment]
lgtm

**Comment by samalba** [comment]
LGTM

**Pull request merged**
