### PR TITLE
add labels to images, networks and volumes

### PR DESCRIPTION
**Pull request by ehazlett**
This adds label support for images (build), networks and volumes.

Refs: https://github.com/docker/engine-api/pull/156

### CODE REVIEW

**Comment by ehazlett** [comment]
Note: I'm still working on getting this tested against docker/docker master but I wanted to get it opened to make sure we have it.

**Comment by vieux** [comment]
Ping @dongluochen

**Comment by dongluochen** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
