### PR TITLE
Switch WriteFlusher import to pkg/ioutils

### PR DESCRIPTION
**Pull request by tianon**
:smile:

https://github.com/docker/docker/pull/13093

### CODE REVIEW

**Comment by tianon** [comment]
As discussed in https://github.com/samalba/dockerclient/pull/103#issuecomment-100033199 :heart:

This fixes the build on master for me, using the following simple `Dockerfile`:
```Dockerfile
FROM golang:1.4

RUN git clone --depth=1 https://github.com/docker/docker.git /go/src/github.com/docker/docker

WORKDIR /go/src/github.com/samalba/dockerclient
COPY . /go/src/github.com/samalba/dockerclient

RUN go get -d -t -v ./...
RUN go build -v ./...
RUN go test -v ./...
```

(and only pre-cloning `docker/docker` for `--depth=1` so it can be speedy)

**Comment by donhcd** [comment]
:+1: ping @abronan @aluzzardi @vieux @ehazlett (sorry for spam)

**Comment by aluzzardi** [comment]
LGTM

**Comment by aluzzardi** [comment]
:+1:

**Pull request merged**
